import React, { Component } from 'react'

export default class About extends Component {
  render() {
    return (
        <div className='container '  style={{marginTop: "12vh"}}>
        <p  >ORIGINALLY CREATED BY A DESIGNER AND A DEVELOPER AT TWITTER, BOOTSTRAP HAS BECOME ONE OF THE MOST POPULAR FRONT-END FRAMEWORKS AND OPEN SOURCE PROJECTS IN THE WORLD. BOOTSTRAP WAS CREATED AT TWITTER IN MID-2010 BY @MDO AND @FAT. PRIOR TO BEING AN OPEN-SOURCED FRAMEWORK, BOOTSTRAP WAS KNOWN AS TWITTER BLUEPRINT. A FEW MONTHS INTO DEVELOPMENT, TWITTER HELD ITS FIRST HACK WEEK AND THE PROJECT EXPLODED AS DEVELOPERS OF ALL SKILL LEVELS JUMPED IN WITHOUT ANY EXTERNAL GUIDANCE. IT SERVED AS THE STYLE GUIDE FOR INTERNAL TOOLS DEVELOPMENT AT THE COMPANY FOR OVER A YEAR BEFORE ITS PUBLIC RELEASE, AND CONTINUES TO DO SO TODAY. ORIGINALLY RELEASED ON FRIDAY, AUGUST 19, 2011, WE’VE SINCE HAD OVER TWENTY RELEASES, INCLUDING TWO MAJOR REWRITES WITH V2 AND V3. WITH BOOTSTRAP 2, WE ADDED RESPONSIVE FUNCTIONALITY TO THE ENTIRE FRAMEWORK AS AN OPTIONAL STYLESHEET. BUILDING ON THAT WITH BOOTSTRAP 3, WE REWROTE THE LIBRARY ONCE MORE TO MAKE IT RESPONSIVE BY DEFAULT WITH A MOBILE FIRST APPROACH. WITH BOOTSTRAP 4, WE ONCE AGAIN REWROTE THE PROJECT TO ACCOUNT FOR TWO KEY ARCHITECTURAL CHANGES: A MIGRATION TO SASS AND THE MOVE TO CSS’S FLEXBOX. OUR INTENTION IS TO HELP IN A SMALL WAY TO MOVE THE WEB DEVELOPMENT COMMUNITY FORWARD BY PUSHING FOR NEWER CSS PROPERTIES, FEWER DEPENDENCIES, AND NEW TECHNOLOGIES ACROSS MORE MODERN BROWSERS. OUR LATEST RELEASE, BOOTSTRAP 5, FOCUSES ON IMPROVING V4’S CODEBASE WITH AS FEW MAJOR BREAKING CHANGES AS POSSIBLE. WE IMPROVED EXISTING FEATURES AND COMPONENTS, REMOVED SUPPORT FOR OLDER BROWSERS, DROPPED JQUERY FOR REGULAR JAVASCRIPT, AND EMBRACED MORE FUTURE-FRIENDLY TECHNOLOGIES LIKE CSS CUSTOM PROPERTIES AS PART OF OUR TOOLING..</p>
    </div>
    )
  }
}
